title       = "nhatot"
baseURL     = "https://nhatot-cli.tamnd.com/"
description = "A command line for nhatot."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/nhatot-cli"
